codecov:
  branch: dev
  bot: codecov-io
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
coverage:
  precision: 1
  round: down
  range: 85..100
  status:
    project:
      default:
        target: auto
        threshold: 5%
 
