# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Stale

on:
  schedule:
    - cron: '13 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: stale-issues
      uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 60
        days-before-close: 7
        days-before-pr-stale: -1
        days-before-pr-close: -1
        remove-stale-when-updated: true
        stale-issue-label: "stale"
        exempt-issue-labels: "no-stale,help-wanted,priority"
        stale-issue-message: >
            There hasn't been any activity on this issue recently.
            Please make sure to update to the latest blinkpy version and
            check if that solves the issue. Let us know if that works for you by
            adding a comment 👍

            This issue has now been marked as stale and will be closed if no
            further activity occurs. Thank you for your contributions.
    - name: stale-pulls
      uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 90
        days-before-close: 7
        days-before-issue-stale: -1
        days-before-issue-close: -1
        remove-stale-when-updated: true
        stale-issue-label: "stale"
        exempt-issue-labels: "no-stale"
        stale-pr-message: >
            There hasn't been any activity on this pull request recently. This
            pull request has been automatically marked as stale because of that
            and will be closed if no further activity occurs within 7 days.

            Thank you for your contributions.
